### ISSUE TITLE
Seems like this gem's 512 result is not the same as phusion / digest-sha3-ruby 

### ISSUE THREAD

**Issue by painforever** [johanns/sha3#10]
If you do:
s = SHA3::Digest::SHA512.new()
s.update("lalala")
s.hexdigest would be:
"89d131506a2bb6d406a15a25ffc477889e2829fe96f3f198c8493f4d58ab1c4f03772ff278caf450e9067e6ab7ac1e5762eda69915f4e1e4c5e66a3c91b94df1"

Whereas if you use https://github.com/phusion/digest-sha3-ruby:
Digest::SHA3.hexdigest("lalala")
would be:
"94040d49dc3fc75bce6c4d585ad4f7b3ce2358759174cb546daaabce11afc63db0eea61c25100b55650fba1afb88452cd65969c4f07956a4380b7ea5f490b306"

They are different, But both claimed that they are Keccak

**Comment by johanns** [comment]
This gems is SHA3 (FIPS 202) implementation of Keccak (https://csrc.nist.gov/publications/detail/fips/202/final), whereas digest-sha3-ruby is reference Keccak implementation (technically not SHA3).
