### ISSUE TITLE
`:SHA512` does not output a correct hash

### ISSUE THREAD

**Issue by Hellfar** [johanns/sha3#7]
Hi,

It seems that the the `:SHA512` does not output a correct hash.
I actually needed to check my hashes through Qt and Rails.
I have test some ways, see:

```C++
QCryptographicHash::hash(QByteArray(QString("foo").toUtf8()), QCryptographicHash::Sha3_512).toHex();
```
`==`
```Ruby
require 'digest/sha3'

Digest::SHA3.hexdigest 'foo'
```
`!=`
```Ruby
require 'sha3'

SHA3::Digest::SHA512.hexdigest 'foo'
```

Haven't test the other lengths so far.

**Comment by johanns** [comment]
Hi @Hellfar. It seems that the QT's SHA3 implementation is not the latest FIPS202 standard, which was introduce with version **1.0.1** of this gem. You can maintain compatibility with QT by using the previous release, version **0.2.6**:

```ruby
gem uninstall sha3 -v 1.0.1
gem install sha3 -v 0.2.6
```

If you have a *Gemfile*, please lock the version:

```ruby
gem 'sha3', '0.2.6'
```

Let me know if this helps.

**Comment by Hellfar** [comment]
Hi @johanns. Yes it does output the same sequence :) !
Thanks
